name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet

      - name: Build Web App
        run: |
          # --base-href: Tells the app that its files are located inside /Typing-Racer/
          # --route-url-strategy hash: Ensures the Flet router works inside a sub-path
          # --yes: Automatically proceeds with Flutter SDK installation
          flet build web . --base-href /Typing-Racer/ --yes --route-url-strategy hash

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/web'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4